server.port: 6003
spring.application.name: trainupdater
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.195.42.68:8761/eureka/

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-out:
          destination: trainupdate
          contentType: application/json
